from __future__ import annotations

import json
import os
from pathlib import Path

import mlflow

from dotenv import load_dotenv


# =========================================================
# 1. CONFIGURATION
# =========================================================

load_dotenv()


TRACKING_URI = os.getenv(
    "MLFLOW_TRACKING_URI",
    "http://127.0.0.1:5000",
)

EXPERIMENT_NAME = os.getenv(
    "MLFLOW_EXPERIMENT_NAME",
    "payflow-payment-success",
)

MODEL_NAME = (
    "payment_success_model"
)

OUTPUT_PATH = Path(
    "artifacts/selected_candidate.json"
)


# =========================================================
# 2. CONNECT TO MLFLOW
# =========================================================

mlflow.set_tracking_uri(
    TRACKING_URI
)


experiment = (
    mlflow.get_experiment_by_name(
        EXPERIMENT_NAME
    )
)


if experiment is None:
    raise RuntimeError(
        f"Experiment not found: "
        f"{EXPERIMENT_NAME}"
    )


experiment_id = (
    experiment.experiment_id
)


# =========================================================
# 3. FIND FINISHED MODEL RUNS
#
# Important:
#
# We select using VALIDATION metrics.
#
# We do NOT inspect test-set results here.
# =========================================================

candidate_runs = mlflow.search_runs(

    experiment_ids=[
        experiment_id
    ],

    filter_string=(
        "attributes.status = 'FINISHED' "
        "AND "
        "tags.problem = 'payment-success' "
        "AND "
        "params.model_type != 'DummyClassifier'"
    ),

    order_by=[
        "metrics.val_failed_f1 DESC",
        "metrics.val_failed_pr_auc DESC",
        "metrics.val_roc_auc DESC",
    ],
)


if candidate_runs.empty:
    raise RuntimeError(
        "No successful candidate runs found."
    )


# =========================================================
# 4. SELECT TOP VALIDATION CANDIDATE
# =========================================================

candidate_row = (
    candidate_runs.iloc[0]
)


candidate_run_id = (
    candidate_row["run_id"]
)


candidate_run_name = (
    candidate_row[
        "tags.mlflow.runName"
    ]
)


candidate_model_type = (
    candidate_row[
        "params.model_type"
    ]
)


# =========================================================
# 5. FIND BASELINE RUN
#
# We keep the DummyClassifier as the reference model.
# =========================================================

baseline_runs = mlflow.search_runs(

    experiment_ids=[
        experiment_id
    ],

    filter_string=(
        "attributes.status = 'FINISHED' "
        "AND "
        "params.model_type = 'DummyClassifier'"
    ),

    order_by=[
        "attributes.start_time DESC"
    ],

    max_results=1,
)


if baseline_runs.empty:
    raise RuntimeError(
        "Dummy baseline run was not found."
    )


baseline_row = (
    baseline_runs.iloc[0]
)


baseline_run_id = (
    baseline_row["run_id"]
)


baseline_run_name = (
    baseline_row[
        "tags.mlflow.runName"
    ]
)


# =========================================================
# 6. FIND LOGGED MODELS
#
# MLflow 3 treats Logged Models as first-class objects.
#
# We find the model created by each selected source run.
# =========================================================

logged_models = (
    mlflow.search_logged_models(

        experiment_ids=[
            experiment_id
        ],

        filter_string=(
            f"name = '{MODEL_NAME}'"
        ),

        output_format="list",
    )
)


def find_ready_model_for_run(
    source_run_id: str,
):
    """
    Find the READY logged model generated by a specific
    MLflow source run.
    """

    matches = []

    for model in logged_models:

        if (
            model.source_run_id
            != source_run_id
        ):
            continue

        # Failed XGBoost logging attempts may have left
        # failed model resources behind.
        #
        # Only use models whose status contains READY.
        status = str(
            getattr(
                model,
                "status",
                "",
            )
        ).upper()

        if "READY" not in status:
            continue

        matches.append(
            model
        )

    if not matches:
        raise RuntimeError(
            "No READY logged model found "
            f"for run {source_run_id}"
        )

    # If a run somehow contains multiple logged models,
    # use the most recently created one.
    matches.sort(
        key=lambda model:
            model.creation_timestamp,
        reverse=True,
    )

    return matches[0]


candidate_model = (
    find_ready_model_for_run(
        candidate_run_id
    )
)


baseline_model = (
    find_ready_model_for_run(
        baseline_run_id
    )
)


# =========================================================
# 7. BUILD MODEL URIS
# =========================================================

candidate_model_uri = (
    f"models:/{candidate_model.model_id}"
)


baseline_model_uri = (
    f"models:/{baseline_model.model_id}"
)


# =========================================================
# 8. CREATE SELECTION DOCUMENT
#
# This becomes an auditable record of why a model moved
# into final test evaluation.
# =========================================================

selection = {

    "experiment_name":
        EXPERIMENT_NAME,

    "selection_dataset":
        "validation",

    "selection_metric":
        "val_failed_f1",

    "candidate": {

        "run_name":
            candidate_run_name,

        "run_id":
            candidate_run_id,

        "model_type":
            candidate_model_type,

        "model_id":
            candidate_model.model_id,

        "model_uri":
            candidate_model_uri,

        "val_failed_f1":
            candidate_row.get(
                "metrics.val_failed_f1"
            ),

        "val_failed_pr_auc":
            candidate_row.get(
                "metrics.val_failed_pr_auc"
            ),

        "val_roc_auc":
            candidate_row.get(
                "metrics.val_roc_auc"
            ),
    },

    "baseline": {

        "run_name":
            baseline_run_name,

        "run_id":
            baseline_run_id,

        "model_id":
            baseline_model.model_id,

        "model_uri":
            baseline_model_uri,
    },
}


# =========================================================
# 9. SAVE SELECTION
# =========================================================

OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True,
)


OUTPUT_PATH.write_text(

    json.dumps(
        selection,
        indent=2,
        default=str,
    ),

    encoding="utf-8",
)


# =========================================================
# 10. TERMINAL SUMMARY
# =========================================================

print()

print(
    "PayFlow AI — Candidate Selected"
)

print(
    "========================================"
)

print(
    f"Run Name : {candidate_run_name}"
)

print(
    f"Model Type: {candidate_model_type}"
)

print(
    f"Run ID   : {candidate_run_id}"
)

print(
    f"Model ID : {candidate_model.model_id}"
)

print(
    f"Model URI: {candidate_model_uri}"
)

print()

print(
    "Baseline"
)

print(
    "----------------------------------------"
)

print(
    f"Run Name : {baseline_run_name}"
)

print(
    f"Run ID   : {baseline_run_id}"
)

print(
    f"Model URI: {baseline_model_uri}"
)

print()

print(
    f"Selection written to: {OUTPUT_PATH}"
)