from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import mlflow
import mlflow.sklearn as mlflow_sklearn

from dotenv import load_dotenv

from mlflow.models import MetricThreshold

# =========================================================
# IMPORTANT FIX
#
# Do NOT use:
#
#     mlflow.exceptions.ModelValidationFailedException
#
# In our installed MLflow version the exception is defined
# in mlflow.models.evaluation.validation.
# =========================================================

from mlflow.models.evaluation.validation import (
    ModelValidationFailedException,
)

from payflow.data.load import (
    load_transactions,
)

from payflow.data.split import (
    chronological_split,
)

from payflow.data.validate import (
    validate_transactions,
)

from payflow.features.payment_success import (
    FEATURE_COLUMNS,
    TARGET_COLUMN,
)

from payflow.models.metrics import (
    calculate_payment_metrics,
)


# =========================================================
# 1. LOAD CONFIGURATION
# =========================================================

load_dotenv()


TRACKING_URI = os.getenv(
    "MLFLOW_TRACKING_URI",
    "http://127.0.0.1:5000",
)


DATA_PATH = Path(
    os.getenv(
        "PAYFLOW_DATA_PATH",
        "data/raw/upi_transactions_2024.csv",
    )
)


SELECTION_PATH = Path(
    "artifacts/selected_candidate.json"
)


EVALUATION_EXPERIMENT = (
    "payflow-model-evaluation"
)


# =========================================================
# 2. CONFIGURE MLFLOW
# =========================================================

mlflow.set_tracking_uri(
    TRACKING_URI
)


mlflow.set_experiment(
    EVALUATION_EXPERIMENT
)


print()
print(
    "MLflow Tracking URI"
)
print(
    "========================================"
)
print(
    mlflow.get_tracking_uri()
)


# =========================================================
# 3. LOAD CANDIDATE SELECTION
#
# This file is generated by:
#
#     scripts/07_select_candidate.py
#
# It tells us exactly which candidate model and baseline
# model should enter final holdout evaluation.
# =========================================================

if not SELECTION_PATH.exists():

    raise FileNotFoundError(
        "Candidate selection file was not found.\n\n"
        "Run this first:\n\n"
        "python scripts/07_select_candidate.py"
    )


selection = json.loads(
    SELECTION_PATH.read_text(
        encoding="utf-8"
    )
)


candidate = (
    selection["candidate"]
)


baseline = (
    selection["baseline"]
)


candidate_model_uri = (
    candidate["model_uri"]
)


baseline_model_uri = (
    baseline["model_uri"]
)


# =========================================================
# 4. DISPLAY SELECTED MODELS
# =========================================================

print()
print(
    "Candidate Selected for Final Evaluation"
)
print(
    "========================================"
)

print(
    f"Run Name : {candidate['run_name']}"
)

print(
    f"Run ID   : {candidate['run_id']}"
)

print(
    f"Model ID : {candidate['model_id']}"
)

print(
    f"Model URI: {candidate_model_uri}"
)


print()
print(
    "Baseline"
)
print(
    "----------------------------------------"
)

print(
    f"Run Name : {baseline['run_name']}"
)

print(
    f"Run ID   : {baseline['run_id']}"
)

print(
    f"Model ID : {baseline['model_id']}"
)

print(
    f"Model URI: {baseline_model_uri}"
)


# =========================================================
# 5. LOAD + VALIDATE DATASET
# =========================================================

df = load_transactions(
    DATA_PATH
)


validate_transactions(
    df
)


# ---------------------------------------------------------
# Normalize original status values.
# ---------------------------------------------------------

df[TARGET_COLUMN] = (
    df[TARGET_COLUMN]
    .astype(str)
    .str.strip()
    .str.upper()
)


# =========================================================
# 6. ENCODE TARGET
#
# FAILED  = 0
# SUCCESS = 1
#
# FAILED is our business event of interest.
# =========================================================

df["target"] = (
    df[TARGET_COLUMN]
    .map(
        {
            "FAILED": 0,
            "SUCCESS": 1,
        }
    )
)


# ---------------------------------------------------------
# Make sure every source status was mapped correctly.
# ---------------------------------------------------------

if df["target"].isna().any():

    unexpected_values = (
        df.loc[
            df["target"].isna(),
            TARGET_COLUMN,
        ]
        .astype(str)
        .unique()
        .tolist()
    )

    raise ValueError(
        "Could not encode all transaction statuses. "
        f"Unexpected values: {unexpected_values}"
    )


df["target"] = (
    df["target"]
    .astype(int)
)


# =========================================================
# 7. RECREATE ORIGINAL CHRONOLOGICAL SPLIT
#
# This must use exactly the same deterministic split logic
# as the training scripts.
#
# TRAIN
#     ↓
# VALIDATION
#     ↓
# TEST
#
# We use only the untouched TEST partition here.
# =========================================================

(
    _,
    _,
    test_df,
) = chronological_split(
    df
)


X_test = (
    test_df[
        FEATURE_COLUMNS
    ]
    .copy()
)


y_test = (
    test_df[
        "target"
    ]
    .copy()
)


# =========================================================
# 8. VERIFY HOLDOUT DATASET
# =========================================================

test_classes = set(
    y_test.unique()
)


if test_classes != {0, 1}:

    raise ValueError(
        "The holdout test set must contain both classes "
        f"0 and 1. Found: {sorted(test_classes)}"
    )


print()
print(
    "Holdout Test Dataset"
)
print(
    "========================================"
)

print(
    f"Rows     : {len(X_test)}"
)

print(
    f"Features : {len(FEATURE_COLUMNS)}"
)

print()
print(
    "Class Distribution"
)

print(
    y_test
    .value_counts()
    .sort_index()
)


# =========================================================
# 9. BUILD MLFLOW EVALUATION DATAFRAME
#
# mlflow.models.evaluate() expects:
#
#     features + target
#
# in one DataFrame.
#
# IMPORTANT:
#
# Do NOT convert categorical columns into fake numeric
# values just for MLflow evaluation.
#
# Our logged sklearn Pipeline contains its own
# OneHotEncoder and expects the original feature values.
# =========================================================

evaluation_data = (
    X_test.copy()
)


evaluation_data[
    "target"
] = (
    y_test.to_numpy()
)


# =========================================================
# 10. MLFLOW EVALUATOR CONFIGURATION
#
# IMPORTANT FIX #1
#
# MLflow's default classifier evaluator normally attempts
# SHAP model explainability.
#
# PayFlow contains categorical/string features such as:
#
#     transaction_type
#     merchant_category
#     sender_bank
#     receiver_bank
#     device_type
#     network_type
#
# MLflow SHAP explainability expects numeric features.
#
# Therefore we disable automatic SHAP explainability.
#
# Standard classifier metrics and plots remain enabled.
# =========================================================

EVALUATOR_CONFIG = {

    # FAILED is represented by 0.
    #
    # We ask the evaluator to treat this as our business
    # class of interest.
    "pos_label": 0,

    # Disable SHAP.
    "log_model_explainability": False,

    # Do not store a SHAP explainer.
    "log_explainer": False,
}


# =========================================================
# 11. LOAD NATIVE SKLEARN PIPELINES
#
# mlflow.models.evaluate() works from model URIs.
#
# We additionally load the native sklearn Pipeline because
# our PayFlow-specific metrics require predict_proba().
# =========================================================

print()
print(
    "Loading candidate model..."
)


candidate_model = (
    mlflow_sklearn.load_model(
        candidate_model_uri
    )
)


print(
    "Candidate loaded successfully."
)


print()
print(
    "Loading baseline model..."
)


baseline_model = (
    mlflow_sklearn.load_model(
        baseline_model_uri
    )
)


print(
    "Baseline loaded successfully."
)


# =========================================================
# 12. CALCULATE PAYFLOW-SPECIFIC METRICS
# =========================================================

def calculate_native_metrics(
    model: Any,
) -> dict[str, float]:
    """
    Calculate PayFlow-specific metrics using the untouched
    holdout test set.

    The MLflow model is a complete sklearn Pipeline:

        raw PayFlow input
               ↓
        preprocessing
               ↓
        classifier

    We explicitly calculate success probabilities so our
    metrics can include:

        ROC-AUC
        Failed PR-AUC
        Failed Precision
        Failed Recall
        Failed F1
        Log Loss
    """

    # -----------------------------------------------------
    # Generate hard predictions.
    # -----------------------------------------------------

    predictions = (
        model.predict(
            X_test
        )
    )


    # -----------------------------------------------------
    # Generate probability matrix.
    # -----------------------------------------------------

    probability_matrix = (
        model.predict_proba(
            X_test
        )
    )


    # -----------------------------------------------------
    # Access fitted classifier.
    # -----------------------------------------------------

    classifier = (
        model
        .named_steps[
            "classifier"
        ]
    )


    classifier_classes = (
        classifier.classes_
    )


    # -----------------------------------------------------
    # We need the probability for SUCCESS=1.
    #
    # Never hard-code [:, 1] without checking the actual
    # class ordering.
    # -----------------------------------------------------

    if 1 not in classifier_classes:

        raise ValueError(
            "Classifier does not contain SUCCESS class 1. "
            f"Classes found: {classifier_classes}"
        )


    success_class_index = (
        list(
            classifier_classes
        )
        .index(1)
    )


    success_probability = (
        probability_matrix[
            :,
            success_class_index,
        ]
    )


    metrics = (
        calculate_payment_metrics(

            y_true=(
                y_test
            ),

            y_pred=(
                predictions
            ),

            success_probability=(
                success_probability
            ),
        )
    )


    # -----------------------------------------------------
    # Convert NumPy numeric scalar values to Python float.
    # This keeps MLflow/JSON serialization predictable.
    # -----------------------------------------------------

    return {

        metric_name:
            float(metric_value)

        for (
            metric_name,
            metric_value,
        )
        in metrics.items()
    }


# =========================================================
# 13. CALCULATE TEST METRICS
# =========================================================

candidate_native_metrics = (
    calculate_native_metrics(
        candidate_model
    )
)


baseline_native_metrics = (
    calculate_native_metrics(
        baseline_model
    )
)


# =========================================================
# 14. START PARENT QUALITY-GATE RUN
#
# Expected hierarchy:
#
# production-quality-gate
#
#     ├── candidate-test-evaluation
#     │
#     └── baseline-test-evaluation
# =========================================================

with mlflow.start_run(
    run_name="production-quality-gate"
) as parent_run:


    # =====================================================
    # 15. PARENT RUN TAGS
    # =====================================================

    mlflow.set_tags(
        {
            "project":
                "payflow-ai",

            "domain":
                "upi-payments",

            "currency":
                "INR",

            "stage":
                "production-evaluation",

            "candidate_run_id":
                candidate[
                    "run_id"
                ],

            "candidate_model_id":
                candidate[
                    "model_id"
                ],

            "baseline_run_id":
                baseline[
                    "run_id"
                ],

            "baseline_model_id":
                baseline[
                    "model_id"
                ],

            "evaluation_dataset":
                "holdout-test",

            "positive_business_class":
                "FAILED=0",

            "shap_explainability":
                "disabled",
        }
    )


    # =====================================================
    # 16. PARENT PARAMETERS
    # =====================================================

    mlflow.log_params(
        {
            "test_rows":
                len(
                    X_test
                ),

            "feature_count":
                len(
                    FEATURE_COLUMNS
                ),

            "candidate_model_uri":
                candidate_model_uri,

            "baseline_model_uri":
                baseline_model_uri,

            "positive_label":
                0,
        }
    )


    # =====================================================
    # 17. CANDIDATE EVALUATION
    # =====================================================

    print()
    print(
        "Evaluating candidate model..."
    )


    with mlflow.start_run(

        run_name="candidate-test-evaluation",

        nested=True,

    ) as candidate_eval_run:


        mlflow.set_tags(
            {
                "role":
                    "candidate",

                "source_run_id":
                    candidate[
                        "run_id"
                    ],

                "source_model_id":
                    candidate[
                        "model_id"
                    ],

                "evaluation_dataset":
                    "holdout-test",

                "shap_explainability":
                    "disabled",
            }
        )


        # -------------------------------------------------
        # IMPORTANT FIX #2
        #
        # Use:
        #
        #     evaluators="default"
        #
        # NOT:
        #
        #     evaluators=["default"]
        #
        # With a single evaluator string MLflow accepts the
        # flat EVALUATOR_CONFIG dictionary above.
        # -------------------------------------------------

        candidate_result = (
            mlflow.models.evaluate(

                model=(
                    candidate_model_uri
                ),

                data=(
                    evaluation_data
                ),

                targets=(
                    "target"
                ),

                model_type=(
                    "classifier"
                ),

                evaluators=(
                    "default"
                ),

                evaluator_config=(
                    EVALUATOR_CONFIG
                ),
            )
        )


        # -------------------------------------------------
        # Log our domain-specific test metrics.
        # -------------------------------------------------

        mlflow.log_metrics(
            {
                f"payflow_{metric_name}":
                    float(metric_value)

                for (
                    metric_name,
                    metric_value,
                )
                in candidate_native_metrics.items()
            }
        )


        # -------------------------------------------------
        # Save the same information as JSON for auditing.
        # -------------------------------------------------

        mlflow.log_dict(
            candidate_native_metrics,
            (
                "payflow/"
                "candidate_metrics.json"
            ),
        )


        print(
            "Candidate evaluation completed."
        )


    # =====================================================
    # 18. BASELINE EVALUATION
    # =====================================================

    print()
    print(
        "Evaluating baseline model..."
    )


    with mlflow.start_run(

        run_name="baseline-test-evaluation",

        nested=True,

    ) as baseline_eval_run:


        mlflow.set_tags(
            {
                "role":
                    "baseline",

                "source_run_id":
                    baseline[
                        "run_id"
                    ],

                "source_model_id":
                    baseline[
                        "model_id"
                    ],

                "evaluation_dataset":
                    "holdout-test",

                "shap_explainability":
                    "disabled",
            }
        )


        baseline_result = (
            mlflow.models.evaluate(

                model=(
                    baseline_model_uri
                ),

                data=(
                    evaluation_data
                ),

                targets=(
                    "target"
                ),

                model_type=(
                    "classifier"
                ),

                evaluators=(
                    "default"
                ),

                evaluator_config=(
                    EVALUATOR_CONFIG
                ),
            )
        )


        mlflow.log_metrics(
            {
                f"payflow_{metric_name}":
                    float(metric_value)

                for (
                    metric_name,
                    metric_value,
                )
                in baseline_native_metrics.items()
            }
        )


        mlflow.log_dict(
            baseline_native_metrics,
            (
                "payflow/"
                "baseline_metrics.json"
            ),
        )


        print(
            "Baseline evaluation completed."
        )


    # =====================================================
    # 19. PRINT AVAILABLE MLFLOW METRICS
    #
    # This is useful while developing the course because
    # MLflow metric naming can vary across versions.
    # =====================================================

    print()
    print(
        "Candidate MLflow Evaluator Metrics"
    )
    print(
        "========================================"
    )


    for metric_name in sorted(
        candidate_result.metrics.keys()
    ):

        print(
            f"  {metric_name}: "
            f"{candidate_result.metrics[metric_name]}"
        )


    print()
    print(
        "Baseline MLflow Evaluator Metrics"
    )
    print(
        "========================================"
    )


    for metric_name in sorted(
        baseline_result.metrics.keys()
    ):

        print(
            f"  {metric_name}: "
            f"{baseline_result.metrics[metric_name]}"
        )


    # =====================================================
    # 20. VERIFY REQUIRED METRICS
    # =====================================================

    required_metrics = {

        "accuracy_score",

        "precision_score",

        "recall_score",

        "f1_score",
    }


    candidate_metric_names = set(
        candidate_result.metrics.keys()
    )


    baseline_metric_names = set(
        baseline_result.metrics.keys()
    )


    missing_candidate_metrics = (
        required_metrics
        - candidate_metric_names
    )


    missing_baseline_metrics = (
        required_metrics
        - baseline_metric_names
    )


    if missing_candidate_metrics:

        raise RuntimeError(
            "Candidate evaluation is missing required "
            f"metrics: {sorted(missing_candidate_metrics)}"
        )


    if missing_baseline_metrics:

        raise RuntimeError(
            "Baseline evaluation is missing required "
            f"metrics: {sorted(missing_baseline_metrics)}"
        )


    # =====================================================
    # 21. QUALITY-GATE CONFIGURATION
    #
    # Current technical policy:
    #
    # Accuracy:
    #
    # Candidate cannot lose more than 2 percentage points
    # compared with baseline.
    #
    # Failed precision:
    #
    # Must improve by at least 0.001.
    #
    # Failed recall:
    #
    # Must improve by at least 0.001.
    #
    # Failed F1:
    #
    # Must improve by at least 0.001.
    #
    # This is an initial engineering gate.
    #
    # Production thresholds will ultimately come from real
    # business costs and SLOs.
    # =====================================================

    baseline_accuracy = float(
        baseline_result.metrics[
            "accuracy_score"
        ]
    )


    allowed_accuracy_drop = (
        0.02
    )


    minimum_candidate_accuracy = max(
        0.0,
        (
            baseline_accuracy
            - allowed_accuracy_drop
        ),
    )


    validation_thresholds = {

        # -------------------------------------------------
        # Overall accuracy.
        # -------------------------------------------------

        "accuracy_score":
            MetricThreshold(

                threshold=(
                    minimum_candidate_accuracy
                ),

                greater_is_better=True,
            ),


        # -------------------------------------------------
        # FAILED precision.
        # -------------------------------------------------

        "precision_score":
            MetricThreshold(

                min_absolute_change=(
                    0.001
                ),

                greater_is_better=True,
            ),


        # -------------------------------------------------
        # FAILED recall.
        # -------------------------------------------------

        "recall_score":
            MetricThreshold(

                min_absolute_change=(
                    0.001
                ),

                greater_is_better=True,
            ),


        # -------------------------------------------------
        # FAILED F1.
        # -------------------------------------------------

        "f1_score":
            MetricThreshold(

                min_absolute_change=(
                    0.001
                ),

                greater_is_better=True,
            ),
    }


    # =====================================================
    # 22. SAVE GATE CONFIGURATION
    # =====================================================

    gate_configuration = {

        "baseline_accuracy":
            baseline_accuracy,

        "allowed_accuracy_drop":
            allowed_accuracy_drop,

        "minimum_candidate_accuracy":
            minimum_candidate_accuracy,

        "minimum_absolute_improvement": {

            "precision_score":
                0.001,

            "recall_score":
                0.001,

            "f1_score":
                0.001,
        },
    }


    mlflow.log_dict(
        gate_configuration,
        (
            "quality_gate/"
            "gate_configuration.json"
        ),
    )


    # =====================================================
    # 23. EXECUTE QUALITY GATE
    #
    # IMPORTANT FIX #3
    #
    # A ModelValidationFailedException means:
    #
    #     CODE WORKED
    #
    # but:
    #
    #     MODEL DID NOT PASS POLICY
    #
    # Therefore we catch this exact MLflow exception and
    # convert it into an auditable FAILED decision.
    # =====================================================

    quality_gate_passed = False

    quality_gate_failure_reason = (
        None
    )


    try:

        mlflow.validate_evaluation_results(

            validation_thresholds=(
                validation_thresholds
            ),

            candidate_result=(
                candidate_result
            ),

            baseline_result=(
                baseline_result
            ),
        )


        # -------------------------------------------------
        # If no exception was raised, every configured
        # quality threshold passed.
        # -------------------------------------------------

        quality_gate_passed = (
            True
        )


        mlflow.set_tag(
            "quality_gate",
            "PASSED",
        )


        mlflow.set_tag(
            "registry_eligible",
            "true",
        )


        mlflow.log_metric(
            "quality_gate_passed",
            1.0,
        )


        print()
        print(
            "========================================"
        )
        print(
            "QUALITY GATE: PASSED"
        )
        print(
            "========================================"
        )


    except ModelValidationFailedException as error:

        # -------------------------------------------------
        # This is not an application crash.
        #
        # The model evaluation completed correctly.
        #
        # The candidate simply did not satisfy one or more
        # quality thresholds.
        # -------------------------------------------------

        quality_gate_passed = (
            False
        )


        quality_gate_failure_reason = (
            str(error)
        )


        mlflow.set_tag(
            "quality_gate",
            "FAILED",
        )


        mlflow.set_tag(
            "registry_eligible",
            "false",
        )


        mlflow.log_metric(
            "quality_gate_passed",
            0.0,
        )


        # -------------------------------------------------
        # Human-readable failure report.
        # -------------------------------------------------

        mlflow.log_text(
            quality_gate_failure_reason,
            (
                "quality_gate/"
                "failure.txt"
            ),
        )


        # -------------------------------------------------
        # Structured failure report.
        # -------------------------------------------------

        mlflow.log_dict(
            {
                "status":
                    "FAILED",

                "candidate_run_name":
                    candidate[
                        "run_name"
                    ],

                "candidate_run_id":
                    candidate[
                        "run_id"
                    ],

                "candidate_model_id":
                    candidate[
                        "model_id"
                    ],

                "baseline_run_name":
                    baseline[
                        "run_name"
                    ],

                "baseline_model_id":
                    baseline[
                        "model_id"
                    ],

                "reason":
                    quality_gate_failure_reason,
            },

            (
                "quality_gate/"
                "failure_details.json"
            ),
        )


        print()
        print(
            "========================================"
        )
        print(
            "QUALITY GATE: FAILED"
        )
        print(
            "========================================"
        )

        print()

        print(
            "The evaluation pipeline completed "
            "successfully."
        )

        print(
            "The MODEL failed one or more "
            "quality requirements."
        )

        print()

        print(
            quality_gate_failure_reason
        )


    # =====================================================
    # 24. BUILD MLFLOW METRIC COMPARISON
    # =====================================================

    evaluator_comparison = {}


    for metric_name in [

        "accuracy_score",

        "precision_score",

        "recall_score",

        "f1_score",

    ]:

        candidate_value = float(
            candidate_result.metrics[
                metric_name
            ]
        )


        baseline_value = float(
            baseline_result.metrics[
                metric_name
            ]
        )


        evaluator_comparison[
            metric_name
        ] = {

            "candidate":
                candidate_value,

            "baseline":
                baseline_value,

            "absolute_change":
                (
                    candidate_value
                    - baseline_value
                ),
        }


    # =====================================================
    # 25. BUILD COMPLETE EVALUATION SUMMARY
    # =====================================================

    evaluation_summary = {

        "evaluation_dataset":
            "holdout-test",

        "test_rows":
            len(
                X_test
            ),

        "feature_count":
            len(
                FEATURE_COLUMNS
            ),

        "positive_business_class":
            "FAILED=0",


        "candidate": {

            "run_name":
                candidate[
                    "run_name"
                ],

            "run_id":
                candidate[
                    "run_id"
                ],

            "model_id":
                candidate[
                    "model_id"
                ],

            "model_uri":
                candidate_model_uri,

            "payflow_test_metrics":
                candidate_native_metrics,
        },


        "baseline": {

            "run_name":
                baseline[
                    "run_name"
                ],

            "run_id":
                baseline[
                    "run_id"
                ],

            "model_id":
                baseline[
                    "model_id"
                ],

            "model_uri":
                baseline_model_uri,

            "payflow_test_metrics":
                baseline_native_metrics,
        },


        "mlflow_evaluator_comparison":
            evaluator_comparison,


        "quality_gate": {

            "passed":
                quality_gate_passed,

            "registry_eligible":
                quality_gate_passed,

            "failure_reason":
                quality_gate_failure_reason,

            "configuration":
                gate_configuration,
        },
    }


    # =====================================================
    # 26. LOG EVALUATION SUMMARY
    # =====================================================

    mlflow.log_dict(
        evaluation_summary,
        (
            "quality_gate/"
            "evaluation_summary.json"
        ),
    )


    # =====================================================
    # 27. PRINT CANDIDATE PAYFLOW METRICS
    # =====================================================

    print()
    print(
        "Candidate — Holdout Test Metrics"
    )
    print(
        "========================================"
    )


    print(
        f"Run Name : "
        f"{candidate['run_name']}"
    )


    print(
        f"Model ID : "
        f"{candidate['model_id']}"
    )


    print()


    for (
        metric_name,
        metric_value,
    ) in candidate_native_metrics.items():

        print(
            f"{metric_name:24s}: "
            f"{metric_value:.6f}"
        )


    # =====================================================
    # 28. PRINT BASELINE PAYFLOW METRICS
    # =====================================================

    print()
    print(
        "Baseline — Holdout Test Metrics"
    )
    print(
        "========================================"
    )


    print(
        f"Run Name : "
        f"{baseline['run_name']}"
    )


    print(
        f"Model ID : "
        f"{baseline['model_id']}"
    )


    print()


    for (
        metric_name,
        metric_value,
    ) in baseline_native_metrics.items():

        print(
            f"{metric_name:24s}: "
            f"{metric_value:.6f}"
        )


    # =====================================================
    # 29. PRINT MLFLOW EVALUATOR COMPARISON
    # =====================================================

    print()
    print(
        "MLflow Evaluator Comparison"
    )
    print(
        "========================================"
    )


    for (
        metric_name,
        metric_values,
    ) in evaluator_comparison.items():

        candidate_value = (
            metric_values[
                "candidate"
            ]
        )


        baseline_value = (
            metric_values[
                "baseline"
            ]
        )


        absolute_change = (
            metric_values[
                "absolute_change"
            ]
        )


        print(
            f"{metric_name:20s} "
            f"candidate={candidate_value:.6f}  "
            f"baseline={baseline_value:.6f}  "
            f"change={absolute_change:+.6f}"
        )


    # =====================================================
    # 30. FINAL GOVERNANCE DECISION
    # =====================================================

    print()
    print(
        "========================================"
    )
    print(
        "FINAL GOVERNANCE DECISION"
    )
    print(
        "========================================"
    )


    if quality_gate_passed:

        print()

        print(
            "ELIGIBLE FOR MODEL REGISTRY"
        )

        print()

        print(
            "The candidate passed the current "
            "PayFlow technical quality gate."
        )

        print()

        print(
            "Next stage:"
        )

        print(
            "MLflow Model Registry"
        )

    else:

        print()

        print(
            "NOT ELIGIBLE FOR MODEL REGISTRY"
        )

        print()

        print(
            "The Python / MLflow evaluation completed "
            "successfully."
        )

        print(
            "The candidate model failed one or more "
            "configured quality thresholds."
        )

        print()

        print(
            "Do not register or promote this candidate "
            "until the model-quality issue is addressed."
        )


    print()
    print(
        "========================================"
    )


    print(
        f"Parent Evaluation Run ID: "
        f"{parent_run.info.run_id}"
    )


    print(
        f"Candidate Evaluation Run ID: "
        f"{candidate_eval_run.info.run_id}"
    )


    print(
        f"Baseline Evaluation Run ID: "
        f"{baseline_eval_run.info.run_id}"
    )


    print(
        "========================================"
    )